version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis
    db:
        image: mysql:8.0
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: your_mysql_password
            MYSQL_ROOT_PASSWORD: your_mysql_root_password
        volumes:
            - ./mysql:/var/lib/mysql
    redis:
        image: redis:latest
        ports:
            - 6381:6379
        volumes:
            - ./redis:/data
