version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - db
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            - REDIS_CLIENT=predis
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=eshop_dev
            - DB_USERNAME=root
            - DB_PASSWORD=password
        volumes:
            - .:/var/www/html
        ports:
            - 8000:8000
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        restart: unless-stopped
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network
        ports:
            - 8889:3306
        environment:
            MYSQL_DATABASE: eshop_dev
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

    redis:
        image: redis:latest
        restart: unless-stopped
        volumes:
            - redisdata:/data
        networks:
            - laravel_network
        ports:
            - 6382:6379
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: redis

    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 9000:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    dbdata:
    redisdata:
